"""onboarding.py — Interactive first-run configuration wizard for exported agents.

After a customer downloads a standalone agent package they run:

    python onboarding.py

The wizard:
  1. Reads config.json (AgentSpec) to know which integrations the agent needs.
  2. Prompts the customer only for the credentials that are actually required.
  3. Writes credentials to .env (never committed to source control).
  4. Verifies that required keys are present before finishing.

The wizard is designed to be embedded inside every exported agent package.
It can also be called programmatically from run_agent.py for first-time setup.

Usage (standalone)
------------------
    python onboarding.py
    python onboarding.py --config path/to/config.json --env path/to/.env

Usage (programmatic)
--------------------
    from cli.onboarding import run_onboarding
    run_onboarding()
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

# ── Helpers ──────────────────────────────────────────────────────────────────

_SEP = "=" * 60


def _print_banner(agent_name: str, agent_purpose: str) -> None:
    print(f"\n{_SEP}")
    print(f"  {agent_name}  —  First-time Setup")
    print(f"  {agent_purpose[:56]}")
    print(f"{_SEP}\n")


def _ask(prompt: str, default: str = "", secret: bool = False) -> str:
    """Prompt user for input, hiding text if secret=True."""
    suffix = f" [{default}]" if default and not secret else ""
    full_prompt = f"  {prompt}{suffix}: "
    try:
        if secret:
            import getpass
            value = getpass.getpass(full_prompt)
        else:
            value = input(full_prompt).strip()
    except (KeyboardInterrupt, EOFError):
        print("\n  Setup cancelled.")
        sys.exit(0)
    return value.strip() or default


def _load_config(config_path: Path) -> dict[str, Any]:
    if config_path.exists():
        try:
            return json.loads(config_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {}


def _load_env(env_path: Path) -> dict[str, str]:
    """Parse existing .env file into a dict."""
    env: dict[str, str] = {}
    if not env_path.exists():
        return env
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, val = line.partition("=")
            env[key.strip()] = val.strip()
    return env


def _save_env(env_path: Path, data: dict[str, str]) -> None:
    """Write .env file preserving comment header."""
    lines = ["# Agent configuration — generated by onboarding.py\n"]
    for key, val in data.items():
        lines.append(f"{key}={val}\n")
    env_path.write_text("".join(lines), encoding="utf-8")


# ── Integration-specific prompts ─────────────────────────────────────────────

_INTEGRATION_PROMPTS: dict[str, list[dict[str, str]]] = {
    "website": [
        {"key": "WEBSITE_URL",    "label": "Website URL (e.g. https://myshop.com)", "secret": "no"},
        {"key": "WEBSITE_API_KEY","label": "Website API key (if required)",          "secret": "yes"},
    ],
    "api": [
        {"key": "API_BASE_URL",   "label": "API base URL",                           "secret": "no"},
        {"key": "API_KEY",        "label": "API key / bearer token",                 "secret": "yes"},
    ],
    "crm": [
        {"key": "CRM_BASE_URL",   "label": "CRM base URL",                           "secret": "no"},
        {"key": "CRM_API_KEY",    "label": "CRM API key",                            "secret": "yes"},
    ],
    "email": [
        {"key": "EMAIL_HOST",     "label": "SMTP host (e.g. smtp.gmail.com)",        "secret": "no"},
        {"key": "EMAIL_PORT",     "label": "SMTP port",    "default": "587",         "secret": "no"},
        {"key": "EMAIL_USER",     "label": "Email address",                          "secret": "no"},
        {"key": "EMAIL_PASSWORD", "label": "Email password / app password",          "secret": "yes"},
    ],
    "slack": [
        {"key": "SLACK_BOT_TOKEN","label": "Slack bot token (xoxb-…)",               "secret": "yes"},
        {"key": "SLACK_CHANNEL",  "label": "Default Slack channel (e.g. #general)",  "secret": "no"},
    ],
    "database": [
        {"key": "DATABASE_URL",   "label": "Database URL (e.g. postgres://…)",       "secret": "yes"},
    ],
    "ecommerce": [
        {"key": "ECOMMERCE_STORE_URL", "label": "Store URL",                         "secret": "no"},
        {"key": "ECOMMERCE_API_KEY",   "label": "Store API key",                     "secret": "yes"},
    ],
    "devops": [
        {"key": "GITHUB_TOKEN",   "label": "GitHub personal access token",           "secret": "yes"},
    ],
    "analytics": [
        {"key": "ANALYTICS_API_KEY", "label": "Analytics platform API key",          "secret": "yes"},
    ],
}

_AI_PROVIDER_PROMPTS = [
    ("github",  "GitHub Models (free, needs GitHub PAT)",     "GITHUB_TOKEN",       "gpt-4.1"),
    ("openai",  "OpenAI",                                      "OPENAI_API_KEY",     "gpt-4o"),
    ("gemini",  "Google Gemini",                               "GEMINI_API_KEY",     "gemini-1.5-flash"),
    ("claude",  "Anthropic Claude",                            "ANTHROPIC_API_KEY",  "claude-sonnet-4-6"),
    ("ollama",  "Ollama (local, no key needed)",               None,                 "qwen2.5-coder:7b"),
]


# ── Core wizard ───────────────────────────────────────────────────────────────

def run_onboarding(
    config_path: str | Path | None = None,
    env_path: str | Path | None = None,
) -> dict[str, str]:
    """
    Run the interactive onboarding wizard.

    Parameters
    ----------
    config_path : path to config.json (defaults to ./config.json)
    env_path    : path to .env output  (defaults to ./.env)

    Returns
    -------
    dict[str, str]
        The configuration dict that was written to .env.
    """
    root = Path(os.path.dirname(os.path.abspath(__file__))).parent
    config_path = Path(config_path) if config_path else root / "config.json"
    env_path = Path(env_path) if env_path else root / ".env"

    config = _load_config(config_path)
    env = _load_env(env_path)

    agent_name = config.get("name", "Agent")
    agent_purpose = config.get("purpose", "Your AI assistant")
    integrations: list[str] = config.get("integrations", [])

    _print_banner(agent_name, agent_purpose)

    # ── Step 1: AI provider ────────────────────────────────────────────────
    print("  STEP 1 — Choose your AI provider\n")
    for i, (pid, desc, _key, _model) in enumerate(_AI_PROVIDER_PROMPTS, 1):
        print(f"  {i}. {desc}")

    while True:
        choice = _ask("\n  Enter number (1–5)", default="1")
        if choice.isdigit() and 1 <= int(choice) <= len(_AI_PROVIDER_PROMPTS):
            break
        print("  Please enter a number between 1 and 5.")

    provider_id, provider_label, key_env, default_model = _AI_PROVIDER_PROMPTS[int(choice) - 1]
    model = _ask(f"  Model name", default=default_model)

    env["AETHEERAI_DEFAULT_PROVIDER"] = provider_id
    env["AETHEERAI_DEFAULT_MODEL"] = model

    if key_env:
        existing = env.get(key_env, "")
        if existing:
            print(f"\n  {key_env} already set — press Enter to keep or type a new value.")
        key_val = _ask(key_env, default=existing, secret=True)
        if key_val:
            env[key_env] = key_val

    # ── Step 2: Integration credentials ───────────────────────────────────
    if integrations:
        print(f"\n  STEP 2 — Integration credentials\n")
        print(f"  This agent connects to: {', '.join(integrations)}\n")

        for integration in integrations:
            prompts = _INTEGRATION_PROMPTS.get(integration.lower(), [])
            if not prompts:
                # Generic fallback
                prompts = [
                    {"key": f"{integration.upper()}_API_KEY",
                     "label": f"{integration.title()} API key",
                     "secret": "yes"},
                ]

            print(f"  -- {integration.upper()} --")
            for p in prompts:
                key = p["key"]
                label = p["label"]
                is_secret = str(p.get("secret", "no")).lower() in ("yes", "true", "1")
                default_val = p.get("default", env.get(key, ""))
                value = _ask(label, default=default_val, secret=is_secret)
                if value:
                    env[key] = value
            print()

    # ── Step 3: Write .env ─────────────────────────────────────────────────
    _save_env(env_path, env)
    print(f"\n  Configuration saved to: {env_path}")

    # ── Step 4: Summary ────────────────────────────────────────────────────
    print(f"\n{_SEP}")
    print(f"  Setup complete! To start your agent:")
    print(f"    python run_agent.py")
    print(f"{_SEP}\n")

    return env


def configure(
    agent_name: str = "Agent",
    extra_prompts: list[dict[str, str]] | None = None,
    env_path: str | Path | None = None,
) -> dict[str, str]:
    """
    Minimal programmatic entry point matching the spec example.

    Extra prompts format:
        [{"key": "MY_KEY", "label": "My service API key", "secret": "yes"}]
    """
    root = Path(os.path.dirname(os.path.abspath(__file__))).parent
    env_path = Path(env_path) if env_path else root / ".env"
    env = _load_env(env_path)

    print(f"\n{_SEP}")
    print(f"  {agent_name} — Configuration")
    print(f"{_SEP}\n")

    for prompt in (extra_prompts or []):
        key = prompt.get("key", "")
        label = prompt.get("label", key)
        is_secret = str(prompt.get("secret", "no")).lower() in ("yes", "true", "1")
        default_val = prompt.get("default", env.get(key, ""))
        value = _ask(label, default=default_val, secret=is_secret)
        if value:
            env[key] = value

    _save_env(env_path, env)
    return env


# ── CLI entry ─────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="AetheerAI Agent — First-time onboarding wizard"
    )
    parser.add_argument(
        "--config", default=None,
        help="Path to config.json (default: ./config.json)"
    )
    parser.add_argument(
        "--env", default=None,
        help="Path to .env output file (default: ./.env)"
    )
    args = parser.parse_args()
    run_onboarding(config_path=args.config, env_path=args.env)


if __name__ == "__main__":
    main()
