"""
reports.py — PDF report generation and CSV/JSON export.

Endpoints
---------
GET  /api/export/csv                   export full prediction history as CSV
GET  /api/export/json                  export history as JSON file download
GET  /api/export/pdf/{prediction_id}   generate a PDF report for one prediction
POST /api/export/pdf/batch             generate a PDF summary for multiple predictions
"""

from __future__ import annotations

import csv
import io
import json
import os
from datetime import datetime
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import Response, StreamingResponse
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from api.auth import get_current_user, get_optional_user
from api.database import Prediction, User, get_db

router = APIRouter(tags=["Reports & Export"])

# ── PDF helpers (uses reportlab; falls back to fpdf2; falls back to plain text) ──

def _build_pdf_reportlab(title: str, sections: list[tuple[str, str]]) -> bytes:
    """Render a simple PDF using ReportLab."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, HRFlowable,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story  = []

    # Title
    title_style = ParagraphStyle(
        "AetheerTitle",
        parent=styles["Heading1"],
        fontSize=20, spaceAfter=6, textColor=colors.HexColor("#6366f1"),
    )
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(
        f"Generated by AetheerAI · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        styles["Normal"],
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    story.append(Spacer(1, 12))

    for section_title, section_body in sections:
        story.append(Paragraph(section_title, styles["Heading2"]))
        story.append(Paragraph(
            section_body.replace("\n", "<br/>") or "—",
            styles["Normal"],
        ))
        story.append(Spacer(1, 8))

    doc.build(story)
    return buf.getvalue()


def _build_pdf_fpdf(title: str, sections: list[tuple[str, str]]) -> bytes:
    """Fallback renderer using fpdf2."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 10, title, ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 6, f"Generated by AetheerAI · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", ln=True)
    pdf.set_draw_color(226, 232, 240)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    for section_title, section_body in sections:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, section_title, ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 6, section_body or "—")
        pdf.ln(4)

    return pdf.output()


def _render_pdf(title: str, sections: list[tuple[str, str]]) -> bytes:
    try:
        return _build_pdf_reportlab(title, sections)
    except ImportError:
        pass
    try:
        return _build_pdf_fpdf(title, sections)
    except ImportError:
        # Ultimate fallback: plain-text "PDF"
        lines = [f"# {title}", f"Generated: {datetime.utcnow().isoformat()}", ""]
        for st, sb in sections:
            lines += [f"## {st}", sb or "—", ""]
        return "\n".join(lines).encode()


def _pred_sections(pred: Prediction) -> list[tuple[str, str]]:
    sections = [
        ("Prediction ID",     str(pred.id)),
        ("Created",           pred.created_at.strftime("%Y-%m-%d %H:%M UTC") if pred.created_at else "—"),
        ("Model",             f"{pred.provider} / {pred.model_used}"),
        ("Status",            pred.status or "—"),
        ("Confidence",        f"{pred.confidence:.1%}" if pred.confidence is not None else "N/A"),
        ("Latency",           f"{pred.latency_ms} ms" if pred.latency_ms else "N/A"),
        ("Cost",              f"${pred.cost_usd:.6f}" if pred.cost_usd else "N/A"),
        ("Tokens Used",       str(pred.tokens_used or "N/A")),
        ("Input",             (pred.input_text or "")[:2000]),
        ("Result",            (pred.result or "")[:4000]),
    ]
    if pred.alternatives:
        alt_text = "\n".join(
            f"  [{i+1}] {a.get('provider')}/{a.get('model')}: "
            f"conf={a.get('confidence','N/A')} lat={a.get('latency_ms','N/A')}ms"
            for i, a in enumerate(pred.alternatives)
        )
        sections.append(("Model Comparison", alt_text))
    if pred.error:
        sections.append(("Error", pred.error))
    return sections


# ── Routes ─────────────────────────────────────────────────────────────────

@router.get("/api/export/csv")
def export_csv(
    db:           Session      = Depends(get_db),
    current_user: User | None  = Depends(get_optional_user),
    limit: int = Query(default=1000, ge=1, le=10_000),
):
    q = db.query(Prediction).order_by(Prediction.created_at.desc())
    if current_user and not current_user.is_admin:
        q = q.filter(Prediction.user_id == current_user.id)
    preds = q.limit(limit).all()

    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "id", "created_at", "provider", "model_used", "status",
        "confidence", "latency_ms", "cost_usd", "tokens_used",
        "input_text", "result", "error",
    ])
    for p in preds:
        writer.writerow([
            p.id,
            p.created_at.isoformat() if p.created_at else "",
            p.provider, p.model_used, p.status,
            p.confidence, p.latency_ms, p.cost_usd, p.tokens_used,
            (p.input_text or "").replace("\n", " ")[:500],
            (p.result     or "").replace("\n", " ")[:500],
            p.error or "",
        ])

    filename = f"aetheer_predictions_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.csv"
    return Response(
        content=buf.getvalue().encode("utf-8"),
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/api/export/json")
def export_json(
    db:           Session      = Depends(get_db),
    current_user: User | None  = Depends(get_optional_user),
    limit: int = Query(default=1000, ge=1, le=10_000),
):
    q = db.query(Prediction).order_by(Prediction.created_at.desc())
    if current_user and not current_user.is_admin:
        q = q.filter(Prediction.user_id == current_user.id)
    preds = q.limit(limit).all()

    payload = json.dumps([p.to_dict() for p in preds], indent=2, ensure_ascii=False)
    filename = f"aetheer_predictions_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.json"
    return Response(
        content=payload.encode("utf-8"),
        media_type="application/json",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/api/export/pdf/{prediction_id}")
def export_pdf_single(
    prediction_id: int,
    db:            Session     = Depends(get_db),
    current_user:  User | None = Depends(get_optional_user),
):
    pred = db.query(Prediction).filter(Prediction.id == prediction_id).first()
    if not pred:
        raise HTTPException(status_code=404, detail="Prediction not found")
    if current_user and not current_user.is_admin and pred.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Access denied")

    pdf_bytes = _render_pdf(
        title=f"AetheerAI Prediction Report #{pred.id}",
        sections=_pred_sections(pred),
    )
    filename = f"aetheer_report_{pred.id}.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


class BatchReportRequest(BaseModel):
    prediction_ids: list[int] = Field(..., min_length=1, max_length=50)


@router.post("/api/export/pdf/batch")
def export_pdf_batch(
    req:          BatchReportRequest,
    db:           Session     = Depends(get_db),
    current_user: User | None = Depends(get_optional_user),
):
    preds = db.query(Prediction).filter(Prediction.id.in_(req.prediction_ids)).all()
    if not preds:
        raise HTTPException(status_code=404, detail="No predictions found")

    # Filter to accessible predictions
    if current_user and not current_user.is_admin:
        preds = [p for p in preds if p.user_id == current_user.id]
    if not preds:
        raise HTTPException(status_code=403, detail="Access denied")

    sections: list[tuple[str, str]] = []
    for pred in sorted(preds, key=lambda p: p.created_at or datetime.min):
        sections.append((f"━━ Prediction #{pred.id} ━━", ""))
        sections.extend(_pred_sections(pred))

    pdf_bytes = _render_pdf(
        title=f"AetheerAI Batch Report ({len(preds)} predictions)",
        sections=sections,
    )
    filename = f"aetheer_batch_report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
